export const ingredientDisplayNames: Record<string, string> = {
  oeufs: "Oeuf(s)",
  sucre: "Sucre",
  farine: "Farine",
  beurre: "Beurre",
  sucre_de_canne: "Sucre de canne",
  eau: "Eau",
  chocolat_noir: "Chocolat noir",
  chocolat_au_lait: "Chocolat au lait",
  praline: "Praliné",
  sucre_vanille: "Sucre vanillé",
  noix: "Noix",
  levure: "Levure",
  sel: "Sel",
  citron_jaune: "Citron jaune",
  citron_vert: "Citron vert",
  maizena: "Maizena",
  noix_de_pecan: "Noix de pécan",
  poudre_de_noisette: "Poudre de noisette",
  sucre_glace: "Sucre glace",
  creme: "Crème",
  myrtilles: "Myrtilles",
  oignon: "Oignon",
  sauce_soja: "Sauce soja",
  aubergine: "Aubergine",
  carotte: "Carotte",
  sesame: "Sésame",
  mirin: "Mirin",
  huile_d_olive: "Huile d'olive",
  vinaigre_balsamique: "Vinaigre balsamique",
  paprika: "Paprika",
  thym: "Thym",
  miel: "Miel",
  lait: "Lait",
  creme_liquide: "Crème liquide",
  lait_concentre: "Lait concentré",
  lait_coco: "Lait de coco",
  noix_de_coco: "Noix de coco",
  banane: "Banane",
  fraises: "Fraises",
  framboises: "Framboises",
  citron: "Citron",
  orange: "Orange",
  pomme: "Pomme",
  poire: "Poire",
  peche: "Pêche",
  mangue: "Mangue",
  ananas: "Ananas",
  raisin: "Raisin",
  figue: "Figue",
  dattes: "Dattes",
  amandes: "Amandes",
  noisettes: "Noisettes",
  pistaches: "Pistaches",
  cannelle: "Cannelle",
  muscade: "Muscade",
  gingembre: "Gingembre",
  vanille: "Vanille",
  extrait_vanille: "Extrait de vanille",
  chocolat_blanc: "Chocolat blanc",
  cacao: "Cacao",
  yaourt: "Yaourt",
  fromage_blanc: "Fromage blanc",
  mascarpone: "Mascarpone",
  ricotta: "Ricotta",
  beurre_de_cacahuete: "Beurre de cacahuète",
  compote: "Compote",
  pain: "Pain",
  brioche: "Brioche",
  pate_feuilletee: "Pâte feuilletée",
  pate_brisee: "Pâte brisée",
  pate_sablee: "Pâte sablée",
  riz: "Riz",
  semoule: "Semoule",
  quinoa: "Quinoa",
  lentilles: "Lentilles",
  pois_chiches: "Pois chiches",
  haricots_rouges: "Haricots rouges",
  courgette: "Courgette",
  poivron: "Poivron",
  champignons: "Champignons",
  epinards: "Épinards",
  brocoli: "Brocoli",
  chou_fleur: "Chou-fleur",
  patate_douce: "Patate douce",
  pomme_de_terre: "Pomme de terre",
  tomates: "Tomates",
  tomates_sechees: "Tomates séchées",
  ail: "Ail",
  echalote: "Échalote",
  basilic: "Basilic",
  coriandre: "Coriandre",
  persil: "Persil",
  menthe: "Menthe",
  romarin: "Romarin",
  curry: "Curry",
  curcuma: "Curcuma",
  piment: "Piment",
  bouillon_legumes: "Bouillon de légumes",
  bouillon_volaille: "Bouillon de volaille",
  sauce_tomate: "Sauce tomate",
  sauce_teriyaki: "Sauce teriyaki",
  vinaigre: "Vinaigre",
  moutarde: "Moutarde",
  ketchup: "Ketchup",
  mayonnaise: "Mayonnaise",
  huile_tournesol: "Huile de tournesol",
  huile_sesame: "Huile de sésame",
  huile_de_colza: "Huile de colza",
  chapelure: "Chapelure",
  fécule_de_pomme_de_terre: "Fécule de pomme de terre",
  bicarbonate: "Bicarbonate",
  colorant: "Colorant",
  poulet: "Poulet",
  boeuf: "Bœuf",
  porc: "Porc",
  dinde: "Dinde",
  lardons: "Lardons",
  jambon: "Jambon",
  saucisse: "Saucisse",
  chorizo: "Chorizo",
  canard: "Canard",
  saumon: "Saumon",
  thon: "Thon",
  crevettes: "Crevettes",
  cabillaud: "Cabillaud",
  moules: "Moules",
  calamars: "Calamars",
  anchois: "Anchois",
  gruyere: "Gruyère",
  comte: "Comté",
  parmesan: "Parmesan",
  emmental: "Emmental",
  mozzarella: "Mozzarella",
  cheddar: "Cheddar",
  feta: "Feta",
  roquefort: "Roquefort",
  bleu: "Bleu",
  lait_avoine: "Lait d’avoine",
  lait_soja: "Lait de soja",
  lait_amande: "Lait d’amande",
  creme_soja: "Crème de soja",
  creme_vegetale: "Crème végétale",
  cumin: "Cumin",
  zaatar: "Zaatar",
  sumac: "Sumac",
  cinq_epices: "Cinq épices",
  herbes_de_provence: "Herbes de Provence",
  tabasco: "Tabasco",
  sauce_huitre: "Sauce huître",
  sauce_bbq: "Sauce BBQ",
  sauce_poisson: "Sauce poisson",
  pois_casses: "Pois cassés",
  haricots_blancs: "Haricots blancs",
  flocons_d_avoine: "Flocons d’avoine",
  boulgour: "Boulgour",
  orge: "Orge",
  polenta: "Polenta",
  tofu: "Tofu",
  seitan: "Seitan",
  tempeh: "Tempeh",
  pain_de_mie: "Pain de mie",
  oeufs_de_lump: "Œufs de lump",
  vinaigre_de_riz: "Vinaigre de riz",
  sirop_d_érable: "Sirop d’érable",
  sirop_d_agave: "Sirop d’agave",
  noisette: "Noisette",
  pignons: "Pignons de pin",
  glacage: "Glaçage",
};

export const getIngredientDisplayName = (enumValue: string): string => {
  return ingredientDisplayNames[enumValue] || enumValue;
};

export const getIngredientEnumValue = (displayName: string): string => {
  const entry = Object.entries(ingredientDisplayNames).find(
    ([_, display]) => display === displayName
  );
  return entry ? entry[0] : displayName;
};

export const getAllIngredientOptions = (): Array<{ value: string; label: string }> => {
  return Object.entries(ingredientDisplayNames).map(([value, label]) => ({
    value,
    label,
  }));
};
